#!/usr/bin/python
# -*- coding: latin-1 -*-
import os, sys




for x in range(2, 6):
  print(x)
for x in range(2, 30, 3):
  print(x)
adj = ["green", "yellow", "red"]
fruits = ["apple", "banana", "cherry"]
for x in adj:
  for y in fruits:
    print(x, y)